### ISSUE TITLE
Problems in building LaGriT in Linux by virtual machine by automatic command

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#101]
Dear all,
I am trying to build LaGriT in Linux by virtual machine by the following command:
./install.sh --release

The command runs for a long time until build netcdf-4.4.1.1, then the following error message displayed:

../../runcmake.sh: 17: [: NO: unexpected operator
../../runcmake.sh: 23: [: OFF: unexpected operator
../../runcmake.sh: 28: [: gnu: unexpected operator
../../runcmake.sh: 32: [: gnu: unexpected operator
../../runcmake.sh: 40: ../../runcmake.sh: cmake: not found

Could anyone give me some hints on how to solve this problem?

In addition, I also tried to build the lg_util seperately, but the following message displayed:
Remove and re-make mm2000.h from mm2000_header.F
rm -f mm2000.h
gcc -E -m64 -Dlinx64 mm2000_header.F -o mm2000.h 
gcc: error trying to exec 'f951': execvp: No such file or directory
Makefile:334: recipe for target 'mm2000.h' failed
make: *** [mm2000.h] Error 1

I used kali-linux-2017.3-vm-amd64.vmx to let LaGriT by built in Linux, could anyone help me to solve this problem?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Thanks. The problem is solved by bypassing Exodus install. And now the Linux version is successfully built.

**Comment by daniellivingston** [comment]
Great! Glad you were able to build. The netCDF build script has given a lot of other people issues too. The main error from your block is: `../../runcmake.sh: 40: ../../runcmake.sh: cmake: not found`. 

On Kali Linux, it's really easy to build cmake: just run `sudo apt-get cmake`

**Comment by TangLaoya** [comment]
That's great. The command is 
sudo apt-get install cmake
Thank you very much.

**Comment by TangLaoya** [comment]
However, this time the following errors displayed:
../../runcmake.sh: 4: [: X/mnt/hgfs/Linshared/LaGriT/LaGriT/TPL/seacas: unexpected operator
../../runcmake.sh: 17: [: NO: unexpected operator
../../runcmake.sh: 23: [: OFF: unexpected operator
../../runcmake.sh: 28: [: gnu: unexpected operator
../../runcmake.sh: 32: [: gnu: unexpected operator
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:13 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
