### ISSUE TITLE
Error message when test example level01\intersect

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#102]
Dear all,
I am testing the Linux version of LaGriT. When I go to LaGriT folder and run the following command:
`./src/lagrit <./test/level01/intersect/input.lgi >out.txt `
the test failed, the error message is below:

    Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

	Backtrace for this error:
	#0  0x555f4ea0850a
	#1  0x555f4ea07b83
	#2  0x7fdfd71c405f
	#3  0x555f4e78b9c2
	#4  0x555f4e5bd158
	#5  0x555f4e580c1b
	#6  0x555f4e57fb1a
	#7  0x555f4e851566
	#8  0x555f4e5bae44
	#9  0x555f4e580c1b
	#10  0x555f4e57fb1a
	#11  0x555f4e57d617
	#12  0x7fdfd71b12e0
	#13  0x555f4e57d4d9
	#14  0xffffffffffffffff
	Segmentation fault
[out.txt](https://github.com/lanl/LaGriT/files/1676295/out.txt)

and the output file is attached.
[out.txt](https://github.com/lanl/LaGriT/files/1676297/out.txt)

However, when I go to  intersect folder and run the following command:
` ../../../src/lagrit <./input.lgi`
the lagrit works successfully.

Could anyone help me to take a look at it?

Thanks,
Tang Laoya

**Comment by millerta** [comment]
Make sure you have write permissions in the directory you are running from.
LaGriT will try to write logx3dgen and outx3dgen files and these will seg fault if you do not have permissions.

Terry

On Jan 29, 2018, at 8:39 PM, TangLaoya <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear all,
I am testing the Linux version of LaGriT. When I go to LaGriT folder and run the following command:
./src/lagrit <./test/level01/intersect/input.lgi >out.txt
the test failed, the error message is below:
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0 0x555f4ea0850a
#1<https://github.com/lanl/LaGriT/issues/1> 0x555f4ea07b83
#2<https://github.com/lanl/LaGriT/issues/2> 0x7fdfd71c405f
#3<https://github.com/lanl/LaGriT/issues/3> 0x555f4e78b9c2
#4<https://github.com/lanl/LaGriT/issues/4> 0x555f4e5bd158
#5<https://github.com/lanl/LaGriT/issues/5> 0x555f4e580c1b
#6<https://github.com/lanl/LaGriT/issues/6> 0x555f4e57fb1a
#7<https://github.com/lanl/LaGriT/issues/7> 0x555f4e851566
#8<https://github.com/lanl/LaGriT/issues/8> 0x555f4e5bae44
#9<https://github.com/lanl/LaGriT/issues/9> 0x555f4e580c1b
#10<https://github.com/lanl/LaGriT/issues/10> 0x555f4e57fb1a
#11<https://github.com/lanl/LaGriT/issues/11> 0x555f4e57d617
#12<https://github.com/lanl/LaGriT/issues/12> 0x7fdfd71b12e0
#13<https://github.com/lanl/LaGriT/issues/13> 0x555f4e57d4d9
#14<https://github.com/lanl/LaGriT/issues/14> 0xffffffffffffffff
Segmentation fault
out.txt<https://github.com/lanl/LaGriT/files/1676295/out.txt>

and the output file is attached.
out.txt<https://github.com/lanl/LaGriT/files/1676297/out.txt>

However, when I go to intersect folder and run the following command:
../../../src/lagrit <./input.lgi
the lagrit works successfully.

Could anyone help me to take a look at it?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear Terry,
Thank you very much for your kindly reply. I think it is not the problem of write permissions, since I also test other examples (test\level01\addmesh_add\input.lgi) and the LaGriT runs OK.

Thanks,
Tang Laoya
