### ISSUE TITLE
PyLaGriT does not support Python3.0+

### ISSUE THREAD

**Issue by daniellivingston** [lanl/LaGriT#111]
When trying to build PyLaGriT using Python version 3.5.5, 

    ❯ python setup.py install
    running install
    running build
    running build_py
    file pylagrit.py (for module pylagrit) not found
    file pexpect.py (for module pexpect) not found
    file __init__.py (for module __init__) not found
    creating build
    creating build/lib
    creating build/lib/pylagrit
    copying pylagrit/__init__.py -> build/lib/pylagrit
    copying pylagrit/pylagrit.py -> build/lib/pylagrit
    creating build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/__init__.py -> build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/ANSI.py -> build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/fdpexpect.py -> build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/FSM.py -> build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/psh.py -> build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/pxssh.py -> build/lib/pylagrit/pexpect
    copying pylagrit/pexpect/screen.py -> build/lib/pylagrit/pexpect
    file pylagrit.py (for module pylagrit) not found
    file pexpect.py (for module pexpect) not found
    file __init__.py (for module __init__) not found
    running install_lib
    creating /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit
    copying build/lib/pylagrit/__init__.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit
    creating /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/__init__.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/ANSI.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/fdpexpect.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/FSM.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/psh.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/pxssh.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pexpect/screen.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect
    copying build/lib/pylagrit/pylagrit.py -> /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/__init__.py to __init__.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/__init__.py to __init__.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/ANSI.py to ANSI.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/fdpexpect.py to fdpexpect.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/FSM.py to FSM.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/psh.py to psh.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/pxssh.py to pxssh.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pexpect/screen.py to screen.cpython-35.pyc
    byte-compiling /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pylagrit.py to pylagrit.cpython-35.pyc
      File "/anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit/pylagrit.py", line 47
        print "Unable to open "+batchfile+": {1}".format(e.strerror)
                              ^
    SyntaxError: invalid syntax

    running install_egg_info
    Writing /anaconda3/envs/distanceMap/lib/python3.5/site-packages/pylagrit-0.0.0-py3.5.egg-info

**Comment by daniellivingston** [comment]
Fixed in 67fba32a7c14983e9a28e55590ed1be0defdae97 and 079deda044ae82a300a7b0e22263edb8b1639965.

    ❯ python test_pylagrit.py
    test_read_script (__main__.TestPyLaGriT) ... ok
    test_convert (__main__.TestPyLaGriT) ... ok
    test_merge (__main__.TestPyLaGriT) ... ok
    test_create (__main__.TestPyLaGriT) ... ok
    test_createpts_brick (__main__.TestPyLaGriT) ... ok
    test_pset_geom (__main__.TestPyLaGriT) ... ok
    test_copy (__main__.TestPyLaGriT) ... ok
    test_pset_not (__main__.TestPyLaGriT) ... ok
    test_subset (__main__.TestPyLaGriT) ... ok

    ----------------------------------------------------------------------
    Ran 9 tests in 8.391s

    OK
    
    ❯ python --version
    Python 3.5.5 :: Anaconda, Inc.

**Comment by Guoyan-Jiang** [comment]
Which version of Python should be used for building PyLaGriT? In my MacOS, I installed two versions of Python: 2.7.17 and 3.7.6_1. The latter was required by installation of LaGriT. When I built PyLaGriT using Python version 2.7.17, it pop up syntax error.


byte-compiling /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylagrit/pexpect/_async.py to _async.pyc
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylagrit/pexpect/_async.py", line 20
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax

byte-compiling /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylagrit/pylagrit.py to pylagrit.pyc
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylagrit/pylagrit.py", line 3406
    def quality(self,*args,quality_type=None,save_att=False):
                                      ^
SyntaxError: invalid syntax

**Comment by daniellivingston** [comment]
@Guoyan-Jiang , PyLaGriT requires Python 3.x. Python 2 was [officially deprecated as of Jan 1st, 2020](https://www.python.org/doc/sunset-python-2/).
