### ISSUE TITLE
tinerator: H_TRANS in buildRefinedTriplane never used

### ISSUE THREAD

**Issue by zgxn** [lanl/LaGriT#114]
As far as I can tell, the variable `delta: float` is used once in `buildRefinedTriplane` (`generate_triplane.py`) to calculate a parameter `h_trans`, which is then transferred to LaGriT input. However, it is not used in neither `user_function.lgi` nor in `user_function2.lgi`.

**Comment by daniellivingston** [comment]
Thanks @zgxn . Removed in latest version of `buildRefinedTriplane`.
