### ISSUE TITLE
Workflow to set Exodus facesets from boundary

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#116]
Workflow development for setting Exodus facesets from boundary polygon.

Here is a toy problem with a stacked mesh and boundary, written outside of pyLaGriT.
All command files included.

https://meshing.lanl.gov/proj/examples/stack_fs_from_bndry/method.html

**Comment by daniellivingston** [comment]
PyLaGriT implementation of top layer faceset capture referenced in 6f9fea78d56b34aee1a275a4c4ec44f5dfd9c7c4. generate_triplane.py: 750-753; 778-796
