### ISSUE TITLE
tinerator : Some delineation methods require additional arguments

### ISSUE THREAD

**Issue by zgxn** [lanl/LaGriT#149]
@daniellivingston 
In the function `watershed_delineation` in `dem_class`, the methods `Holmgren` and `Freeman` require specification of an exponent. Currently, tinerator does not provide a way of doing it. A possible fix would be to add an optional argument `exponent:float` to the method, and propagate it downwards. I have verified that using an `exponent` argument for methods that do not require one, e.g. 'D8' creates no conflict in RichDEM.

**Comment by daniellivingston** [comment]
Great point and thanks for picking up this oversight. We'll have to figure out some way to manage this in interactive node.

Fixed in #150 - closing
