### ISSUE TITLE
[tinerator] : example is out of date

### ISSUE THREAD

**Issue by zgxn** [lanl/LaGriT#154]
@daniellivingston 

The `basic_example.py`-file that shows how to use TINerator is pretty out of date and doesn't work with the newest version anymore.

**Comment by daniellivingston** [comment]
Removed in 42f6c38c6b9fb5d6c879c24ad88e4b8b8911e2c8. That file is really, really out of date. I'll be pushing some Jupyter-based examples to the repo shortly, along with putting them on [MyBinder](https://mybinder.org) when I get the chance

**Comment by zgxn** [comment]
Sounds good, thanks!
