### ISSUE TITLE
[tinerator] generateFacesets method does not work

### ISSUE THREAD

**Issue by zgxn** [lanl/LaGriT#155]
@daniellivingston 

The method `generateFaceSetsNaive` in `dem_class.py` is not implemented. It should probably make a call to `facesets.py` at some point. `generateComplexFacesets` is also not implemented.

It might be better to name the methods more consistently, either `generateNaiveFacesets` or vice versa.

**Comment by daniellivingston** [comment]
Good catch, you're right, that's deprecated in favor of `tin.facesets.basic()/sidesets()/from_elevations()`

**Comment by zgxn** [comment]
Ahh, I see. Thanks!
