### ISSUE TITLE
'PyLaGriT' object has no attribute 'lagrit_exe'

### ISSUE THREAD

**Issue by pinshuai** [lanl/LaGriT#172]
I was running the tinerator docker image on a remote server. I can import tinerator, but got the following error when I tried to load the example file.

<img width="1120" alt="Screenshot 2019-08-01 16 55 31" src="https://user-images.githubusercontent.com/34693887/62334652-63d00680-b47d-11e9-954d-2569aec2e5c9.png">

Any idea?

**Comment by daniellivingston** [comment]
Hi Pin - can you verify that the file [`~/.pylagritrc`](https://lanl.github.io/LaGriT/pylagrit/original/gettingstarted.html#installation) exists?

**Comment by pinshuai** [comment]
Yes, this is the content.
```
lagrit_exe : "/home/jovyan//bin/lagrit"
```

**Comment by daniellivingston** [comment]
Interesting. Can you try running, either in Jupyter or in the REPL,

```
from pylagrit import PyLaGriT

lg = PyLaGriT()
```

If this is a PyLaGriT issue, which it seems to be, you should get the same traceback as above.

**Comment by pinshuai** [comment]
I did get the same error. Btw, I am running the notebook on a remote server like NERSC.

<img width="892" alt="Screenshot 2019-08-09 16 11 20" src="https://user-images.githubusercontent.com/34693887/62813566-5c81ac00-bac0-11e9-9162-b40a14efd762.png">

**Comment by daniellivingston** [comment]
@dharp , can you look at this?

**Comment by dharp** [comment]
It looks like pylagrit is not finding your pylagritrc file. Try adding a lagrit_exe option to the PyLaGriT instantiation: lg = PyLaGriT(lagrit_exe=<path/to/your/lagrit/ext>). I added an check for a missing lagrit_exe in the code now that dumps a message with the above suggestion. Not sure why it isn't finding your ~/.pylagritrc, but this is a workaround for now.

**Comment by dharp** [comment]
Another thing to try is to put the .pylagritrc file in the directory where you are running the script. pylagrit will look in that location first before looking for it in your home directory. I'm wondering if it is possible that the terminal that you are running the script from does not know where your home directory is?

**Comment by pinshuai** [comment]
@dharp Sorry for the delay. Adding `lagrit_exe=<path/to/your/lagrit/ext>` did work for creating a Pylagrit object. However, tinerator wraps everything and I am not sure if I can add the path directly so tinerator knows where to find it. 

I also tried putting `~/.pylagritrc` file in both working dir and home dir, but no luck so far.

Is there a way I can hardwire the lagrit_exe path in the source code?

**Comment by pinshuai** [comment]
This bug has been fixed by using double quote in the path.  #See #179
