### ISSUE TITLE
TINerator Error: LaGriT executable is not defined

### ISSUE THREAD

**Issue by pinshuai** [lanl/LaGriT#179]
I have compiled LaGriT on my mac and created a `.pylagritrc` file under my home directory. I also installed tinerator and pylagrit and was able to import those into a Jupyter notebook. But when I ran the following code, I got an error saying it could not find the lagrit executable. 

<img width="1131" alt="Screenshot 2019-11-05 14 22 59" src="https://user-images.githubusercontent.com/34693887/68251350-cb937180-ffd7-11e9-866b-61f03652fa93.png">

This is what's in the `.pylagritrc` file.
```
lagrit_exe : '/Users/shua784/Dropbox/github/LaGriT/src/lagrit'
```
I also tried putting `.pylagritrc` file in my working directory, but still got the same problem.

Any idea?

**Comment by daniellivingston** [comment]
@pinshuai , can you try replacing the single quotes in your LaGriT path with double-quotes and let me know if that works? I.e.:

```
lagrit_exe : "/Users/shua784/Dropbox/github/LaGriT/src/lagrit"
```

**Comment by mhannonj** [comment]
For what it's worth, I was running into the same issues, and replacing the path with double quotes fixed it.

**Comment by pinshuai** [comment]
It worked! Such an easy fix...

**Comment by daniellivingston** [comment]
I agree that this is confusing though: we're operating in Python, where both `"` and `'` represent string literals, and so it follows that either should work. I'll get a patch pushed when I have a free minute.
