### ISSUE TITLE
[Tinerator] layered mesh shows incorrect order and material ids

### ISSUE THREAD

**Issue by pinshuai** [lanl/LaGriT#183]
I am using the `build_layered_mesh` function in tinerator to generate stacked meshes, however, I got weird results when visualizing in Paraview.

```
tckness = np.repeat(np.array([0.5, 1]), [2, 9], axis=0)
mat_ids = np.repeat(np.array([5, 1]), [2, 9], axis=0)

my_dem.build_layered_mesh(tckness, matids=mat_ids)
```

I want to generate two thin layers on top and nine thick layers below, and I have assigned material id=5 for the thin layer and material id=1 for the thick layer. 

This is what I have seen in Paraview. It seems like only one thin layer is generated on top instead of two. Also the material id is mismatched. 

<img width="943" alt="Screenshot 2019-11-11 11 44 24" src="https://user-images.githubusercontent.com/34693887/68617228-aab99900-047b-11ea-8ebc-c26df2285257.png">

**Comment by daniellivingston** [comment]
@pinshuai , this was addressed in 1728baae85641c2da6c7b978f747f2d5130121e7. Closing this issue for now, please re-open if that commit doesn't solve the problem.
