### ISSUE TITLE
Issues running level02 and level03 tests

### ISSUE THREAD

**Issue by mhannonj** [lanl/LaGriT#185]
I ran into an issue when trying to test out the installation ('make test').  It appears that, for level02 and level03, the default output file in my case was 'lagrit.out'.  It appears the tests were looking for a file named 'outx3dgen', so they automatically failed.  However, when I ran a couple of the cases in level02 (exodus_cube and exodus_prism) manually ('lagrit < input.lgi') and ran the command 'diff lagrit.out ./reference/outx3dgen', the outputs appeared identical after the timestamp information provided in the header of the files.

Is there something I'm missing when running 'make test', do you think?  Or does the test file (suite.py) need to be edited to account for the default lagrit output?

**Comment by daniellivingston** [comment]
Fixed in #193.
