### ISSUE TITLE
Why is pexpect included in the source?

### ISSUE THREAD

**Issue by banesullivan** [lanl/LaGriT#195]
Why is pexpect's source code included in the PyLaGriT package?

From a quick glance, it isn't modified (is it?). Why not just list it as a dependency in the `setup.py`?

If a specific version is needed, you can set that in the `setup.py`.

**Comment by dharp** [comment]
Hi Bane,

Yes, all good advice. In the beginning, I just packaged it with PyLaGriT to avoid having to deal with dependencies. Since the pexpect that we include does everything we need, I guess I’m still leaning towards just leaving it as is and avoiding dependency issues. I will keep the suggestion in mind though as we move forward.

Thanks,
Dylan

**Comment by banesullivan** [comment]
I went ahead with a PR to take it out and use `pip` to manage the dependency (see #196) - installing the package this way is painless. 

Having `pexpect` included in the repo has no advantage: it just adds more files to the repo and confusion for new developers looking to modify the source. Also, this brings inconsistency as `numpy` is a requirement too. If including `pexpect`, why not include `numpy`? 

And soon I will add some routines to have 3D visualization with PyVista for #161 and having PyVista as an optional dependency in the `setup.py`. Having all of this managed by pip will make the installation process much simpler for end-users.

I'm willing to put in the time to properly set up the Python package to follow best practices. Also, I would like to set up the build process so the `lagrit` binary and Python interface can easily be shipped to PyPI for easy installation.

**Comment by dharp** [comment]
Sounds good. Thanks for all the efforts. BTW, who are you?

Dylan

**Comment by banesullivan** [comment]
I'm a developer for @pyvista, a geophysicist, and at the moment I'd like to see LaGriT grow in the Python ecosystem. I've interacted with @daniellivingston here in the past

**Comment by dharp** [comment]
Great, good to have you working with us Bane!

Thanks,
Dylan

**Comment by daniellivingston** [comment]
Thanks @banesullivan !
