### ISSUE TITLE
Tutorial of "Regions and Points to Tetrahedral Mesh" failed

### ISSUE THREAD

**Issue by S-Nari** [lanl/LaGriT#197]
Hi. I'm very new to Lagrit.
I tried the tutorial for making a cube with tetrahedral meshes, but that failed.
A error message appeared in the section 7 "Connect the points into tetrahedra" as follows;

$ cmo/setall/itp/pset,get,rayend/21/                                            
$ ERROR CMO: invalid option: setall                                               
$  ERROR CMO: setall  itp     -1        

I checked the lagrid command manual, and found that there is no command "setall".
Alternatively, how should I do? 
I would appreciated if you let me know some knowledge about this error.

Best regards, 

S. Narita

**Comment by daniellivingston** [comment]
@S-Nari Thanks for noticing this! It should actually be `setaTT`, not `setaLL`:

```
cmo/setatt//itp/pset,get,rayend/21/
```

Updated the tutorial accordingly.

Also, we have a more comprehensive tutorial online that I recommend you check out instead: https://lanl.github.io/LaGriT/pages/tutorial/stratigraphy/index.html
