### ISSUE TITLE
Trouble with LaGriT installation on Ubuntu 20.04.1LTS

### ISSUE THREAD

**Issue by Michele985** [lanl/LaGriT#210]
Hi, I'm trying to install LaGriT to use it with PyLaGriT on Ubuntu 20.04.1LTS. To do this, I run the following commands but I can't complete the installation. Could you please help me? thank you so much

O.S. Ubuntu 20.04.1 LTS

michele@demic:~ sudo apt-get install gcc
gcc è già alla versione più recente (4:9.3.0-1ubuntu2).
(Translation: gcc is already updated at the latest version (4:9.3.0-1ubuntu2).)

michele@demic:~ sudo apt-get install g++
g++ è già alla versione più recente (4:9.3.0-1ubuntu2).

michele@demic:~ sudo apt-get install gfortran
gfortran è già alla versione più recente (4:9.3.0-1ubuntu2).

michele@demic:~ sudo apt-get install cmake
cmake è già alla versione più recente (3.16.3-1ubuntu1).

michele@demic:~ sudo apt-get install git
git è già alla versione più recente (1:2.25.1-1ubuntu3).

michele@demic:~ sudo apt-get install bash
bash è già alla versione più recente (5.0-6ubuntu1.1).

michele@demic:~ sudo apt-get install wget
wget è già alla versione più recente (1.20.3-1ubuntu1).

michele@demic:~ sudo apt-get install python3
python3 è già alla versione più recente (3.8.2-0ubuntu2).

michele@demic:~ sudo apt-get install m4
m4 è già alla versione più recente (1.4.18-4).

michele@demic:~ sudo apt-get install bison
bison è già alla versione più recente (2:3.5.1+dfsg-1).

michele@demic:~ sudo apt-get install libz-dev
Nota, viene selezionato "zlib1g-dev" al posto di "libz-dev"
(Translation: Note "zlib1g-dev" is selected instead of "libz-dev")
zlib1g-dev è già alla versione più recente (1:1.2.11.dfsg-2ubuntu1.1).

michele@demic:~ git clone https://github.com/lanl/LaGriT.git
michele@demic:~ cd Lagrit

michele@demic:~/LaGriT sudo make exodus
….
Exodus successfully built!
Build directory:
/home/michele/LaGriT/seacas/lib
echo "To compile LaGriT with Exodus, append the above"; \
echo "path to LD_LIBRARY_PATH (on Linux) or DYLD_LIBRARY_PATH (on Mac)";\
echo "and run \"make [options] [target]\"."; \
echo ""; \
echo "Alternately, run"; \
echo "  make EXO_LIB_DIR=/home/michele/LaGriT/seacas/lib [target]"
To compile LaGriT with Exodus, append the above
path to LD_LIBRARY_PATH (on Linux) or DYLD_LIBRARY_PATH (on Mac)
and run "make [options] [target]".
Alternately, run
  make EXO_LIB_DIR=/home/michele/LaGriT/seacas/lib [target]

michele@demic:~/LaGriT  sudo nano ~/.profile
I added at the end of the file the string below:
export LD_LIBRARY_PATH=/home/michele/LaGriT/seacas/lib

michele@demic:~/LaGriT  . ~/.profile

michele@demic:~/LaGriT echo $LD_LIBRARY_PATH
/home/michele/LaGriT/seacas/lib

michele@demic:~/LaGriT  sudo make exodus
Output is the same as described above

michele@demic:~/LaGriT sudo make release
dumpexodusII.f:130: Error: Can't open included file 'exodusII.inc'
make[1]: *** [Makefile:147: objects/dumpexodusII.o] Errore 1
make[1]: uscita dalla directory «/home/michele/LaGriT/src»
make: *** [Makefile:186: before] Errore 2

The installation guide suggest that: ”This problem typically results from a failed Exodus compilation”.
I tried to follow the solutions on the guide but nothing happens, the problem is always there.

**Comment by daniellivingston** [comment]
Hi @Michele985 , thanks for reaching out. This is indeed a known problem with Exodus compilation. I've opened an issue on the topic here: https://github.com/gsjaardema/seacas/issues/190

In the meantime, you can build LaGriT without Exodus:

```
$ make clean
$ make release WITH_EXODUS=0
$ src/lagrit
```

**Comment by daniellivingston** [comment]
I just pushed a commit (b54e70a8d5a923a72a888fc33ff2149771e03cf1) that should resolve this issue. Can you try again (with Exodus)?

**Comment by Michele985** [comment]
Hi @daniellivingston , thank you for your quick reply.
I used the last version of the code and I run it with Exodus.
In this case, make exodus and make release work good.
Make test returns the following message:
All checks complete, 1 directories failed out of 41
make: *** [Makefile:200: test] Errore 1.
The PyLaGriT Simple Example shows the expected results.
Do you think the problems are finally solved?
Thank you again.

**Comment by daniellivingston** [comment]
Hi @Michele985 , yes, you should be good to go! I will need to fix that test case but the integrity of the code itself is fine. Closing this issue for now. Thanks!
