### ISSUE TITLE
fix build and tests

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#226]
make sure all tests are working on the different platforms

**Comment by daniellivingston** [comment]
See also #230

**Comment by daniellivingston** [comment]
modify test script to skip exodus test if not built with exodus
also for new libs as added

**Comment by millerta** [comment]
level01 changed to include all tests that do not require external libs.
level02 changed to contain tests for external libs, such as exodus.
All gmv binary files removed or replaced with avs ascii files.
Many extra unnecessary files removed from the test suite.
level03 is for student, developer tests and has not been updated yet (not part of auto-tests)
