### ISSUE TITLE
Update `level03->lin_extp` test 

### ISSUE THREAD

**Issue by daniellivingston** [lanl/LaGriT#230]
Update test (slow from IO) at:

    LaGriT/test/level03/lin_extp/input.lgi

**Comment by millerta** [comment]
level03 directory is for students and developer tests and not included in the auto-test scripts
Check these tests and remove any that are no longer relevant.
Move anything that should be in auto-test into level01
Remove extra files, especially gmv binary files.

**Comment by millerta** [comment]
Fix level03 to avoid git warnings:

```
Checking out files: 100% (3142/3142), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'test/level03/read_3token/reference/test.AvS'
  'test/level03/read_3token/reference/test.avs'
  'test/level03/read_3token/reference/test.InP'
  'test/level03/read_3token/reference/test.inp'
  'test/level03/read_3token/test.AvS'
  'test/level03/read_3token/test.avs'
  'test/level03/read_3token/test.InP'
  'test/level03/read_3token/test.inp'
```

**Comment by millerta** [comment]
removed all unnecessary or redundant tests
copied read_gocad tests into level01, these examples are used in dfnWorks and Jewelsuite projects.
A 3D TETRA example remains here in level03, either example or code needs to fix neg volumes.
