### ISSUE TITLE
documentation page width too wide

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#254]
For some reason the documentation pages are not displaying a good width.
The top banner has important links clipped on the right side.
The only way I can see those links and get to the search function, is to reduce display size.
See attached image with banner clipped, and reduced to access the right side options.

<img width="1276" alt="Screen Shot 2024-01-05 at 11 32 43 AM" src="https://github.com/lanl/LaGriT/assets/21063624/d212920a-8207-49d5-8d4e-fe63630fa0a3">

<img width="1300" alt="Screen Shot 2024-01-05 at 11 33 38 AM" src="https://github.com/lanl/LaGriT/assets/21063624/f60f3e99-b4ea-480f-b206-98498b3cca97">

**Comment by ehinrichs** [comment]
Documentation page width fixed.
