### ISSUE TITLE
Dudded Points Spacing

### ISSUE THREAD

**Issue by hymanjd** [lanl/LaGriT#53]
For large numbers of dudded points, over 1000000, there is no space between text FILTER:Dudding and the number of duplicate points.

**Comment by millerta** [comment]
Changed from i7 to i10 similar to other formats in the code.
Moved count value to end of statement.

FILTER:Dudding duplicate points:    16000008                                    

replaced version:

FILTER:Dudding******* duplicate points.

Format changed in files: filter.f, filterkd.f, connect2d_lg.f, connect.f
