### ISSUE TITLE
Fix test suite scripts

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#60]
test/suite.py has options that are not working on linux, fix these.
test/level01/check_test.py should ignore banner differences and not report them

**Comment by daniellivingston** [comment]
`test/suite.py` has been completely revised in [`192b94f`](https://github.com/lanl/LaGriT/commit/192b94f8799ffec3440bf294d1c24bccacba165d) to work for all arguments and all combinations of arguments. 

`test/level01/check_test.py` has been updated in [d61cb35](https://github.com/lanl/LaGriT/commit/d61cb35306326d7f487bcb46fae3ecc1e0b7464c) to no longer see `date_compile` and other small header lines as errors.

Closed.
