### ISSUE TITLE
add compile flags for more efficient build process

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#61]
Replace clunky build process steps with flags on the compile line.
-noexodus flag to build without the external ExodusII libs. Currently a no exodus file is copied to the file calling exodus. Use ifdef statements to exclude the exodus call instead. Default includes exodus.
-V3.202 (or something similar) to remove all the lagrit_*.h files and generate lagrit.h at compile time.

**Comment by millerta** [comment]
For this release, remove all lagrit_*.h files. Keep lagrit_linux.h, lagrit_mac.h, lagrit_win.h
Version should be 3.202 with a June 2017 compile date.
Add compiler type to end of compile data, ie gcc5.2 or whatever is used for the compile.

Work on compile auto-generate for lagrit banner during next release.

**Comment by daniellivingston** [comment]
For the second comment: resolved in [`725a266`](https://github.com/lanl/LaGriT/commit/725a2663cc236a67e08981daff55d784c3e8e5b3).
