### ISSUE TITLE
Is there any Windows OS support for this mesher?

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#64]
Dear administrator,
I got to know that LaGriT is a very powerful mesher for multi-scaled domains. However, I found that it is built and run in Linux system. Is there any support for Windows OS?

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Hi @TangLaoya , 

Compilation on Windows is possible, though at this time, it is not officially supported. I recommend downloading a Linux shell, such as MinGW or Cygwin, and trying to build within that. Make sure that you have gcc (with gfortran and g++), make, git, wget, tar, and unzip installed, and you should be able to use the install.sh script in the root directory of LaGriT. You may have to modify the install script and Makefiles in src/ and lg_util/src/.

Please let me know if you attempt to build LaGriT on Windows, along with any problems or successes.

cc: @millerta

**Comment by TangLaoya** [comment]
Dear Daniel,

Thank you very much for your kindly reply. I will try it latter. But it
could be difficult for me to download and install Cygwin, etc..
Is it possible to create a CMakefile.txt so that we can generate VS project
by CMake?

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Unfortunately, there are no immediate plans to implement CMake, due largely to the complexity of building Exodus.

Some options:
1. Take a look at this pull request: https://github.com/lanl/LaGriT/pull/48 . A contributor wrote CMake files for LaGriT and Exodus, but I couldn't get them to work for me. You might have better luck. Please let me know if you do.
2.  You can take a look at the documentation we have for building on Windows; however, this requires Cygwin: https://github.com/lanl/LaGriT/blob/master/documentation/build_win.txt
3. You can attempt to write your own CMake files. If they work, especially cross-platform, follow the directions [for external contributors](https://github.com/lanl/LaGriT/blob/master/CONTRIBUTING.md) and more likely than not we would merge your files to master.
