### ISSUE TITLE
Add point type element output to AVS output format

### ISSUE THREAD

**Issue by cwgable** [lanl/LaGriT#65]
I believe when Paraview reads an AVS *.inp file if you have vertices in the vertex list that do not appear in the cell connectivity list, you cannot view them. I believe the fix would be to modify the AVS (dumps) subroutine so that you could turn on an option that would include an unconnected vertex as a cell of type point (pt).

I think the default should stay the way it is but perhaps add a flag or option that would cause this to occur.

Possible syntax:
dump / avs_womesh / filename.inp / moname / 

This syntax is parallel to:
rmpoint / womesh

eg.
1 0. 0. 0.
2 1. 0. 0.
3 1. 1. 0.
4 1. 1. 1.
1 1 tri 1 2 3
2 2 pt 4

**Comment by millerta** [comment]
This has been implemented with following syntax:
dump/avs/ file.inp/ cmo_name / 1 3 1 1 or any variation with 3 as second iopt value.
