### ISSUE TITLE
Modify install/build to use correct ExodusII include files

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#69]
Remove exodusII.h  exodusII.inc  exodusII_int.h  exodusII_int.inc from src directory.
Scripts should point to or copy these files from ${ACCESS}/include 
Make sure exodusII.inc exists and has definition for EX_ELEM_SET

Current build uses exodusII.inc from old ExodusII because it does not exist in ${ACCESS}/include
Getting the correct fortran include files for ExodusII may resolve this warning:

EXODUS: Warning: This code was compiled with exodusII version 6.02,
          but was linked with exodusII library version 6.36
          This is probably an error in the build process of this code.

**Comment by daniellivingston** [comment]
Fixed in latest install.sh push.
