### ISSUE TITLE
connect: 2D Delaunay not guarnteed without call to recon/0

### ISSUE THREAD

**Issue by cwgable** [lanl/LaGriT#75]
There are cases where one can use connect to connect a 2D planar point distribution and the resulting mesh will not be Delaunay. This can be fixed with a call to recon/0.

Fix:
At the end of a successful execution of connect (2D) there should be a hard wired call:
call dotask ( "recon / 0" )

**Comment by millerta** [comment]
Added call to recon 0 using dotask in msgtty after the call to connect for 2D.
Testing is not showing any differences except for added lines of reporting.
The test suite will have to be updated with these new outx3dgen files.

< recon/0                                                                         
< RECON2D reconnection loop2d:     1                                              
< RECON: done.                                                                    
< finish                                                                          
< LaGriT FINISH: recon 0 for connect 2d

**Comment by millerta** [comment]
Updated test directories to new outx3dgen with recon 0 after connect.

**Comment by millerta** [comment]
Connect fails to connect 10 points and duds them all. This causes recon/0 to fail with memory errors and Infinity value:
36        epsilonv REAL     scalar          scalar const perma   l   Infinity 
See files in /project/eesdev/tam/LaGriT/work/connect_bug
