### ISSUE TITLE
Tag files to track website completion

### ISSUE THREAD

**Issue by deknapp** [lanl/LaGriT#77]
@millerta @cwgable @daniellivingston 

To help track progress on the website, please do the following:

If you are editing a file, and when you are done, it seems ok for the public eye, add the following lines at the top of the file:

        ---
        title: (add title if not already there)
        tags: ok
        ---

If the file looks decent but still needs more review, write:

      ---
      title: (add title if not already there)
      tags: review
      ---

If the file / page is bad and not ready to be on the website, do not add a tag. 

I have written a script in /docs/edit_scripts/ called get_site_map.py that generates a coded site map and site list. The list and the site map are coded this way:

**BOLD** - page is good
_Italic_ - page still needs review
Crossed out - page is bad / not ready for website

**Comment by millerta** [comment]
Add tags with more meaning, ie good, bad, needs work, default= needs review
Change all font to bold for good, bad italics, all others regular font
See if we can allow author comments int header portion
