### ISSUE TITLE
Fix all broken links

### ISSUE THREAD

**Issue by deknapp** [lanl/LaGriT#79]
@millerta @daniellivingston 

This website finds all broken links for free:

http://www.brokenlinkcheck.com/broken-links.php

 I haven't had time to fix all of the broken links yet, so thought I would point out the website if you have time.

**Comment by millerta** [comment]
Another link checker with verbose results.
https://www.deadlinkchecker.com/website-dead-link-checker.asp

**Comment by millerta** [comment]
This should be done soon to avoid all the bad and extra pages that search is pulling up.

**Comment by millerta** [comment]
Removed many files that were duplicate old copies and resolved unlinked files.
This was a global fix and remaining bad links and old unused files will be discovered and fixed as found.
I used scripts to find problem files, these are in LaGriT/docs/edit_scripts

Most old duplicate files were located in /pages/docs and were removed
The good copies of files were are located in /pages/docs/commands and sub directories.
