### ISSUE TITLE
Several questions about using LaGriT

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#89]
Dear all,
I have several questions about using LaGriT: 
1) Can I compiling the LaGriT under Windows 7 64bit + VS2013 + Intel Fortran?
2) Can I use LaGriT without ExodusII, is there any preprocessor to set to include or exclude ExodusII related code?
3) Is there any quick method to let LaGriT accept data format like OFF or Tetgen's .poly and then mesh the objects?

Thanks,
Tang Laoya

**Comment by millerta** [comment]
Regarding your questions on compiling LaGriT, read instructions under documents/INSTALL.md for various platforms. We do not use LaGriT here on WINDOWS, but other users have used these instructions to compile for their systems. The instructions include how to compile without the Exodus routines. Direct your questions and comments regarding LaGriT builds to our team member Daniel Livingston.

**Comment by millerta** [comment]
Regarding your question on input file formats for LaGriT, see the manual at https://lagrit.lanl.gov/docs/commands/READ.html
Though we do not have a reader specifically for OFF or tetgen, you may find it easy to convert those formats to AVS UCD ascii format.
http://vis.lbl.gov/NERSC/Software/express/help6.2/help/reference/dvmac/UCD_Form.htm

<pre>
# 
# Simple AVS UCD File 
# 
8 1 1 0 0 <­­8 nodes, 1 cell, 1 component of node data 
1 0.000 0.000 1.000 <­­Node coordinates 
2 1.000 0.000 1.000 
3 1.000 1.000 1.000 
4 0.000 1.000 1.000 
5 0.000 0.000 0.000 
6 1.000 0.000 0.000 
7 1.000 1.000 0.000 
8 0.000 1.000 0.000 
1 1 hex 1 2 3 4 5 6 7 8 <­­cell id, material id, cell type, cell vertices 
1 1 <­­num data components, size of each component 
stress, lb/in**2 <­­Component name, units name 
1 4999.9999 <­­Data value for each node component 
2 18749.9999 
3 37500.0000 
4 56250.0000 
5 74999.9999 
6 93750.0001 
7 107500.0003 
8 5000.0001 

</pre>

**Comment by TangLaoya** [comment]
Dear millerta,
Thank you very much for your kindly reply. Now I have successfully built the LaGriT (I have put all Fortran source code in LaGriT-master\lg_util\src and LaGriT-master\src into one project ) as a static library under Windows 7 64bit + VS2013 + Intel Fortran. 

Now my problem is that: where can I find an example driver code to let the LaGriT to read an input data (such as you said the AVS UCD data) and then generate hex or tet mesh in the whole region with different domains?

Thanks,
Tang Laoya
