### ISSUE TITLE
Where to find simple driver code to let the LaGriT work?

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#91]
Dear all,
Where can I find an example driver code to let the LaGriT to read an input data (such as the AVS UCD data) and then generate hex or tet mesh in the whole region with different domains (materials)? Currently I only find all kinds of command examples for different operations, is there a simple and full example (Fortran code) to drive the LaGriT to read input data, and then generate hex or tet mesh? 

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Hi Tang, 

The only place in LaGriT that you need to worry about Fortran is during the compilation process. Once you launch the LaGriT binary, you use LaGriT's [custom syntax](http://lagrit.lanl.gov/commands_cat.shtml) to build and manipulate your mesh.
(There are exceptions to this; i.e. you can use LaGriT's functions as a library within your own Fortran/C code [by calling dotask()](http://lagrit.lanl.gov/docs/issuing.html), or write your own function by editing [the user_sub function](http://lagrit.lanl.gov/docs/writing.html)).

Without knowing what your input data looks like, it's hard for me to answer your question. I would suggest using the [read command like this example](http://lagrit.lanl.gov/docs/commands/cmo/cmo_readatt.html), running [connect](http://lagrit.lanl.gov/docs/commands/CONNECT1.html), and then using [dump](http://lagrit.lanl.gov/docs/commands/DUMP2.html) to save the mesh. This creates a tetrahedral mesh.

If you send a sample of your data and what you are trying to do with it I can help more.
